In [1]:
from go import go_board
import numpy as np
from collections import deque, Counter
from termcolor import colored

def convert_liberty_list(liberties,board_size=9):
    new_liberties = np.zeros((board_size,board_size))
    for i in range(board_size):
        for j in range(board_size):
            new_liberties[i,j] = liberties[i,j][0]
    return new_liberties

def check_board_group_liberties(test, right_board, right_groups, right_liberties):
    num_test_failed = 0
    # Check board
    if np.array_equal(test.board,right_board):
        print(colored("Board test succesfull", "green"))
    else:
        num_test_failed += 1
        print(colored("Board test failed", "red"))

        
    # Check liberties
    if np.array_equal(convert_liberty_list(test.liberties), right_liberties):
        print(colored("Liberty test succesfull", "green"))
    else:
        num_test_failed += 1
        print(colored("Liberty test failed", "red"))
    return num_test_failed

# Board initializing test
num_test_failed = 0
test = go_board(9)
print("***** Board initialising tests *****")
board = np.zeros((9,9),dtype="int8")

groups = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])
liberties = np.array([[2., 3., 3., 3., 3., 3., 3., 3., 2.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [2., 3., 3., 3., 3., 3., 3., 3., 2.]])

num_test_failed += check_board_group_liberties(test, board, groups, liberties)

# Basic test
print("***** Basic tests *****")
board = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

groups = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

liberties = np.array([[2., 3., 3., 3., 3., 3., 3., 3., 2.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 3., 4., 4., 4., 3.],
       [3., 4., 4., 3., 4., 3., 4., 4., 3.],
       [3., 4., 4., 4., 3., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [2., 3., 3., 3., 3., 3., 3., 3., 2.]])
test.move((4,4),"black")
num_test_failed += check_board_group_liberties(test, board, groups, liberties)

# group test
print("***** Group tests *****")
test.move((4,3),"black")
test.move((3,3),"black")
test.move((3,4),"white")

board = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
                   [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
                   [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
                   [ 0,  0,  0,  1, -1,  0,  0,  0,  0],
                   [ 0,  0,  0,  1,  1,  0,  0,  0,  0],
                   [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
                   [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
                   [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
                   [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])
groups = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 3, 4, 0, 0, 0, 0],
                   [0, 0, 0, 3, 3, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0]])
liberties = np.array([[2., 3., 3., 3., 3., 3., 3., 3., 2.],
                   [3., 4., 4., 4., 4., 4., 4., 4., 3.],
                   [3., 4., 4., 3., 3., 4., 4., 4., 3.],
                   [3., 4., 3., 6., 2., 3., 4., 4., 3.],
                   [3., 4., 3., 6., 6., 3., 4., 4., 3.],
                   [3., 4., 4., 3., 3., 4., 4., 4., 3.],
                   [3., 4., 4., 4., 4., 4., 4., 4., 3.],
                   [3., 4., 4., 4., 4., 4., 4., 4., 3.],
                   [2., 3., 3., 3., 3., 3., 3., 3., 2.]])
num_test_failed += check_board_group_liberties(test, board, groups, liberties)


# capture test test
print("***** Capture tests *****")
print ("Non-self capture test")
test.move((3,5),"black")
test.move((2,4),"white")
board = np.array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

groups = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 6, 0, 0, 0, 0],
       [0, 0, 0, 3, 6, 5, 0, 0, 0],
       [0, 0, 0, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])
liberties = np.array([[2., 3., 3., 3., 3., 3., 3., 3., 2.],
       [3., 4., 4., 4., 3., 4., 4., 4., 3.],
       [3., 4., 4., 2., 3., 2., 4., 4., 3.],
       [3., 4., 3., 6., 3., 3., 3., 4., 3.],
       [3., 4., 3., 6., 6., 2., 4., 4., 3.],
       [3., 4., 4., 3., 3., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [3., 4., 4., 4., 4., 4., 4., 4., 3.],
       [2., 3., 3., 3., 3., 3., 3., 3., 2.]])
num_test_failed += check_board_group_liberties(test, board, groups, liberties)

print("Double capture")
test.move((1,4),"white")
test.move((0,4),"white")
test.move((0,3),"black")
test.move((0,5),"black")
test.move((1,5),"black")
test.move((2,5),"black")
test.move((1,3),"black")
test.move((2,3),"black")

board = np.array([[0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])
groups = np.array([[ 0,  0,  0, 14,  0, 12,  0,  0,  0],
       [ 0,  0,  0, 14,  0, 12,  0,  0,  0],
       [ 0,  0,  0, 14,  0, 12,  0,  0,  0],
       [ 0,  0,  0, 14,  0, 12,  0,  0,  0],
       [ 0,  0,  0, 14, 14,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])
liberties = np.array( [[ 2.,  3.,  2., 12.,  1.,  9.,  2.,  3.,  2.],
                       [ 3.,  4.,  3., 12.,  2.,  9.,  3.,  4.,  3.],
                       [ 3.,  4.,  3., 12.,  2.,  9.,  3.,  4.,  3.],
                       [ 3.,  4.,  3., 12.,  1.,  9.,  3.,  4.,  3.],
                       [ 3.,  4.,  3., 12., 12.,  2.,  4.,  4.,  3.],
                       [ 3.,  4.,  4.,  3.,  3.,  4.,  4.,  4.,  3.],
                       [ 3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  3.],
                       [ 3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  3.],
                       [ 2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  2.]])


num_test_failed += check_board_group_liberties(test, board, groups, liberties)


# Check Ko rule
print("Checking Ko")
#test.move((4,5),"black")
test = go_board(9)
test.move((1,4),"black")
test.move((2,3),"black")
test.move((2,5),"black")
test.move((3,4),"black")
test.move((3,3),"white")
test.move((3,5),"white")
test.move((4,4),"white")
test.move((2,4),"white")


black_ko_board = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])
white_ko_board = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

if (np.array_equal(test.get_legal_board("black"),black_ko_board)):
    print(colored("Ko obeyd", "green"))

else:
    print(colored("Ko not obeyd succesfull", "red"))

if (np.array_equal(test.get_legal_board("white"),white_ko_board)):
    print(colored("Ko correctly ignored", "green"))

else:
    print(colored("Ko should have been ignored", "red"))

"""
print("blackboard was:")
print(test.get_legal_board("black"))
print("black board should have benn:")
print(black_ko_board)

print("white  was:")
print(test.get_legal_board("white"))
print("white board should have benn:")
print(white_ko_board)
"""
# Legal moves checker
print("Checking legal move checker")
#test.move((4,5),"black")
test = go_board(9)
if (test.get_legal_board("black")[3,5]==0):
    print("test failed")
test.move((3,5),"black")
if (test.get_legal_board("white")[5,2]==0):
    print("test failed")
test.move((5,2),"white")
if (test.get_legal_board("black")[6,4]==0):
    print("test failed")
test.move((6,4),"black")
if (test.get_legal_board("white")[3,3]==0):
    print("test failed")
test.move((3,3),"white")
if (test.get_legal_board("black")[2,3]==0):
    print("test failed")
test.move((2,3),"black")
if (test.get_legal_board("white")[2,2]==0):
    print("test failed")
test.move((2,2),"white")
if (test.get_legal_board("black")[4,3]==0):
    print("test failed")
test.move((4,3),"black")
if (test.get_legal_board("white")[3,2]==0):
    print("test failed")
test.move((3,2),"white")
if (test.get_legal_board("black")[3,4]==0):
    print("test failed")
test.move((3,4),"black")
if (test.get_legal_board("white")[4,7]==0):
    print("test failed")
test.move((4,7),"white")
if (test.get_legal_board("black")[4,2]==0):
    print("test failed")
test.move((4,2),"black")
if (test.get_legal_board("white")[4,1]==0):
    print("test failed")
test.move((4,1),"white")
if (test.get_legal_board("black")[5,3]==0):
    print("test failed")
test.move((5,3),"black")
if (test.get_legal_board("white")[5,1]==0):
    print("test failed")
test.move((5,1),"white")
if (test.get_legal_board("black")[3,7]==0):
    print("test failed")
test.move((3,7),"black")
if (test.get_legal_board("white")[4,6]==0):
    print("test failed")
test.move((4,6),"white")
if (test.get_legal_board("black")[3,6]==0):
    print("test failed")
test.move((3,6),"black")
if (test.get_legal_board("white")[6,6]==0):
    print("test failed")
test.move((6,6),"white")
if (test.get_legal_board("black")[1,3]==0):
    print("test failed")
test.move((1,3),"black")
if (test.get_legal_board("white")[1,2]==0):
    print("test failed")
test.move((1,2),"white")
if (test.get_legal_board("black")[6,2]==0):
    print("test failed")
test.move((6,2),"black")
if (test.get_legal_board("white")[6,1]==0):
    print("test failed")
test.move((6,1),"white")
if (test.get_legal_board("black")[7,6]==0):
    print("test failed")
test.move((7,6),"black")
if (test.get_legal_board("white")[7,5]==0):
    print("test failed")
test.move((7,5),"white")
if (test.get_legal_board("black")[7,7]==0):
    print("test failed")
test.move((7,7),"black")
if (test.get_legal_board("white")[6,5]==0):
    print("test failed")
test.move((6,5),"white")
if (test.get_legal_board("black")[7,4]==0):
    print("test failed")
test.move((7,4),"black")
if (test.get_legal_board("white")[8,4]==0):
    print("test failed")
test.move((8,4),"white")
if (test.get_legal_board("black")[8,3]==0):
    print("test failed")
test.move((8,3),"black")
if (test.get_legal_board("white")[8,5]==0):
    print("test failed")
test.move((8,5),"white")
if (test.get_legal_board("black")[6,7]==0):
    print("test failed")
test.move((6,7),"black")
if (test.get_legal_board("white")[7,3]==0):
    print("test failed")
test.move((7,3),"white")
if (test.get_legal_board("black")[7,2]==0):
    print("test failed")
test.move((7,2),"black")
if (test.get_legal_board("white")[8,2]==0):
    print("test failed")
test.move((8,2),"white")
if (test.get_legal_board("black")[7,1]==0):
    print("test failed")
test.move((7,1),"black")
if (test.get_legal_board("white")[5,5]==0):
    print("test failed")
test.move((5,5),"white")
if (test.get_legal_board("black")[4,5]==0):
    print("test failed")
test.move((4,5),"black")
if (test.get_legal_board("white")[5,7]==0):
    print("test failed")
test.move((5,7),"white")
if (test.get_legal_board("black")[3,8]==0):
    print("test failed")
test.move((3,8),"black")
if (test.get_legal_board("white")[8,1]==0):
    print("test failed")
test.move((8,1),"white")
if (test.get_legal_board("black")[7,0]==0):
    print("test failed")
test.move((7,0),"black")
if (test.get_legal_board("white")[5,4]==0):
    print("test failed")
test.move((5,4),"white")
if (test.get_legal_board("black")[6,3]==0):
    print("test failed")
test.move((6,3),"black")
if (test.get_legal_board("white")[4,4]==0):
    print("test failed")
test.move((4,4),"white")
if (test.get_legal_board("black")[8,3]==0):
    print("test failed")
test.move((8,3),"black")
if (test.get_legal_board("white")[6,8]==0):
    print("test failed")
test.move((6,8),"white")
if (test.get_legal_board("black")[8,0]==0):
    print("test failed")
test.move((8,0),"black")
if (test.get_legal_board("white")[7,8]==0):
    print("test failed")
test.move((7,8),"white")
if (test.get_legal_board("black")[1,5]==0):
    print("test failed")
test.move((1,5),"black")
if (test.get_legal_board("white")[8,7]==0):
    print("test failed")
test.move((8,7),"white")
if (test.get_legal_board("black")[6,0]==0):
    print("test failed")
test.move((6,0),"black")
if (test.get_legal_board("white")[1,0]==0):
    print("test failed")
test.move((1,0),"white")
if (test.get_legal_board("black")[2,1]==0):
    print("test failed")
test.move((2,1),"white")
if (test.get_legal_board("white")[4,0]==0):
    print("test failed")
test.move((4,0),"black")
if (test.get_legal_board("black")[3,0]==0):
    print("test failed")
test.move((3,0),"white")
if (test.get_legal_board("white")[5,0]==0):
    print("test failed")
test.move((5,0),"black")
if (test.get_legal_board("black")[3,1]==0):
    print("test failed")
test.move((3,1),"white")
if (test.get_legal_board("white")[0,2]==0):
    print("test failed")
test.move((0,2),"black")
if (test.get_legal_board("black")[0,1]==0):
    print("test failed")
test.move((0,1),"white")
if (test.get_legal_board("white")[0,3]==0):
    print("test failed")
test.move((0,3),"black")
if (test.get_legal_board("black")[4,8]==0):
    print("test failed")
test.move((4,8),"white")

print("Checking game score counter")
if (test.count_points()==5.5):
    print(colored("Counted score was correct ", "green"))

else:
    print(colored("Counted score was correct not correct", "red"))

    
    
# Check if copying of game works
old_board = np.copy(test.get_legal_board("black"))
old_liberties = np.copy(convert_liberty_list(test.liberties))

new_test = test.copy_game()
test.move((0,8),"black")



print("Checking game copy mechanism")
if np.array_equal(convert_liberty_list(new_test.liberties), old_liberties):
    print(colored("Liberties copied correctly ", "green"))
else:
    print(colored("Liberties was not copied correctly", "red"))
    
if np.array_equal(new_test.get_legal_board("black"), old_board):
    print(colored("Board copied correctly ", "green"))
else:
    print(colored("Board was not copied correctly", "red"))

***** Board initialising tests *****
Board test succesfull
Liberty test succesfull
***** Basic tests *****
Board test succesfull
Liberty test succesfull
***** Group tests *****
Board test succesfull
Liberty test succesfull
***** Capture tests *****
Non-self capture test
Board test succesfull
Liberty test succesfull
Double capture
Board test succesfull
Liberty test succesfull
Checking Ko
Ko obeyd
Ko correctly ignored
Checking legal move checker
Checking game score counter
Counted score was correct 
Checking game copy mechanism
Liberties copied correctly 
Board copied correctly 


In [2]:
test = go_board(9)
test.move((1,4),"white")
test.move((0,4),"white")
test.move((0,3),"black")
test.move((0,5),"black")
test.move((1,5),"black")
test.move((2,5),"black")
test.move((1,3),"black")
test.move((2,3),"black")
test.board

array([[ 0,  0,  0,  1, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int8)

In [3]:
test.get_state("white")[15,:,:]

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [5]:
test.get_state("white").shape

(17, 9, 9)

In [6]:
test.move((1,5),"black")
test.get_legal_board("white")
test.count_points()

74.5

In [1]:
test = go_board(9)
test.move((1,4),"black")
test.move((2,3),"black")
test.move((2,5),"black")
test.move((3,4),"black")
test.move((3,3),"white")
test.move((3,5),"white")
test.move((4,4),"white")
test.move((2,4),"white")
print(test.board)

NameError: name 'go_board' is not defined

In [2]:
deque([(4, 4), (2, 4), (3, 5), (3, 3)])
deque([(3, 4), (1, 4), (2, 5), (2, 3)])
deque([(2, 4), (0, 4), (1, 5), (1, 3)])
deque([(1, 4), (0, 5), (0, 3)])


test = go_board(9)
test.move((1,4),"black")
test.move((0,4),"black")
test.move((0,2),"black")
test.move((1,2),"black")
test.move((2,2),"black")
test.move((2,3),"black")
test.move((0,6),"black")
test.move((1,6),"black")
test.move((2,6),"black")
test.move((2,5),"black")
test.move((3,4),"white")
test.move((2,4),"black")

In [2]:
#test.move((4,5),"black")
test = go_board(9)
test.move((1,4),"black")
test.move((2,3),"black")
test.move((2,5),"black")
test.move((3,4),"black")
test.move((3,3),"white")
test.move((3,5),"white")
test.move((4,4),"white")
test.move((2,4),"white")
print("board")
print(test.board)
print("groups")
print(test.groups)
print("liberties")
print(convert_liberty_list(test.liberties))
test.get_legal_board("black")

board
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0  0]
 [ 0  0  0  1 -1  1  0  0  0]
 [ 0  0  0 -1  0 -1  0  0  0]
 [ 0  0  0  0 -1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]
groups
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 2 8 3 0 0 0]
 [0 0 0 5 0 6 0 0 0]
 [0 0 0 0 7 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
liberties
[[2. 3. 3. 3. 2. 3. 3. 3. 2.]
 [3. 4. 4. 2. 3. 2. 4. 4. 3.]
 [3. 4. 3. 2. 1. 2. 3. 4. 3.]
 [3. 4. 3. 3. 0. 3. 3. 4. 3.]
 [3. 4. 4. 2. 4. 2. 4. 4. 3.]
 [3. 4. 4. 4. 3. 4. 4. 4. 3.]
 [3. 4. 4. 4. 4. 4. 4. 4. 3.]
 [3. 4. 4. 4. 4. 4. 4. 4. 3.]
 [2. 3. 3. 3. 3. 3. 3. 3. 2.]]


array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [2]:
test

In [13]:
test = go_board(9)
test.move((3,5),"black")

In [16]:
test.get_legal_board("black")

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

5.5

True

In [20]:
"""
print("board")
print(test.board)
print("groups")
print(test.groups)
print("liberties")
print(convert_liberty_list(test.liberties))
test.get_legal_board("black")
"""

0

In [5]:
point_board = test.board
        
# set neutral positions to value 3, to mark as unexplored
for i in range(9):
    for j in range(9):
        if (point_board[i,j]==0):
            point_board[i,j] = 3
print(point_board)
new_point_board, new_area, new_black, new_white = test.map_area(point_board, test.board_size, (3,4), deque([]), 0, 0)
print(new_black)
print(new_white)

[[ 3  3  3  3  3  3  3  3  3]
 [ 3  3  3  3  1  3  3  3  3]
 [ 3  3  3  1 -1  1  3  3  3]
 [ 3  3  3 -1  3 -1  3  3  3]
 [ 3  3  3  3 -1  3  3  3  3]
 [ 3  3  3  3  3  3  3  3  3]
 [ 3  3  3  3  3  3  3  3  3]
 [ 3  3  3  3  3  3  3  3  3]
 [ 3  3  3  3  3  3  3  3  3]]
0
1


In [4]:
from collections import deque, Counter

In [5]:
neigh = deque([1,2,3,4])
C = Counter()
print(Counter(neigh))

Counter({1: 1, 2: 1, 3: 1, 4: 1})


In [3]:
for element in neigh:
    C[element] += 1
print(C)

Counter({1: 1, 2: 1, 3: 1, 4: 1})


In [2]:
test1 = deque([(1,2), (3,4), (10,9), (7,8), (2,3)])
test2 = deque([2, 4, 6, 8])
test3 = deque([0, 10])
test1+=test2
print(test1)

deque([(1, 2), (3, 4), (10, 9), (7, 8), (2, 3), 2, 4, 6, 8])


In [6]:
deque(map(test.get_neighbours_fast,[(2,3), (5,8)]))

deque([[(3, 3), (1, 3), (2, 4), (2, 2)], [(6, 8), (4, 8), (5, 7)]])

In [19]:
a = np.arange(6).reshape(2,3)
b = np.ones((2,3))
it = np.nditer(a, flags=['multi_index'], op_flags=['writeonly'])
with it:
    while not it.finished:
        it[0] = b[it.multi_index[0],it.multi_index[1]]
        it.iternext()
a

1
1
1
1
1
1


array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
a = np.arange(6).reshape(2,3)
a
test1 = [(1,2), (0,1), (1,0)]

In [11]:
a[tuple(zip(*test1))]

array([5, 1, 3])

In [3]:
index_list = tuple([(0,1), (0,0), (1,1)])
a[index_list]

IndexError: too many indices for array

In [29]:
liberties = np.array([1,2,3])
colors = np.array([1,-1,1])

(np.logical_xor(liberties<2,colors==1))


array([False, False,  True])

In [20]:
colors

array([ 1, -1,  1])

In [3]:
def test_func(x):
    return x[0]*(x[1]>2)

In [7]:
np.array(list(map(test_func, a)))

array([0, 3])

[array([9, 9])]

In [2]:
test_list = [1, 2, 2, 3, 3, 3, 4, 5, 5]

In [4]:
C = Counter(test_list)

In [11]:
list(C.items())

[(1, 1), (2, 2), (3, 3), (4, 1), (5, 2)]

In [20]:
from collections import deque, Counter
def solution(data, n):
    # Count number of occurences with a counter
    C = Counter(data)
    C = list(C.items())
    # Construct the elements to be removed
    black_list = deque([])
    for element in C:
        if element[1]>n:
            black_list.append(element[0])
    # Construct the returned list by running over data
    new_data = deque([])
    for entry in data:
        if entry not in black_list:
            new_data.append(entry)
    return list(new_data)

In [24]:
test1 = [1,2,3,4,5]
test2 = [10,11,12,13,14]

for index, value in test1,test2:
    print("Index was", index, "value was", value)

ValueError: too many values to unpack (expected 2)

In [5]:
np.array(list(map(test_func, np.ndenumerate(a))))

/Users/tirsgaard/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  


array([(), (), (), (1, 0), (1, 1), (1, 2)], dtype=object)

In [ ]:
from collections import deque, Counter
def solution(data, n):
    C = Counter(data)
    C = list(C.items())
    black_list = deque([])
    for element in C:
        if element[1]>n:
            black_list.append(element[0])
    new_data = deque([])
    for entry in data:
        if entry not in black_list:
            new_data.append(entry)
    return new_data